apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-api.fullname" . }}
  labels: {{- include "edge-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
  selector: {{- include "edge-api.selectorLabels" . | nindent 4 }}
