apiVersion: v1
kind: Service
metadata:
  name: {{ include "retrieval.fullname" . }}
  labels: {{- include "retrieval.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector: {{- include "retrieval.selectorLabels" . | nindent 4 }}
