apiVersion: v1
kind: Service
metadata:
  name: {{ include "tools.fullname" . }}
  labels: {{- include "tools.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
  selector: {{- include "tools.selectorLabels" . | nindent 4 }}
